### ISSUE TITLE
[Bug] GmsCore crashes upon starting

### ISSUE THREAD

**Issue by 813ethan** [ReVanced/GmsCore#146]
GmsCore crashes upon open
system: Evolution X 9.3 17/08 update (not rooted)
device: Redmi Note 12 Turbo 
microg version: 0.3.1.4.240913
crash log:
```
java.lang.IllegalArgumentException: Cursor for query content://app.revanced.android.gms.microg.settings/exposureNotification [exposure_scanner_enabled] was null
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.gms/org.microg.gms.ui.MainSettingsActivity}: android.view.InflateException: Binary XML file line #46 in app.revanced.android.gms:layout/settings_root_activity: Binary XML file line #46 in app.revanced.android.gms:layout/settings_root_activity: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3993)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.view.InflateException: Binary XML file line #46 in app.revanced.android.gms:layout/settings_root_activity: Binary XML file line #46 in app.revanced.android.gms:layout/settings_root_activity: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #46 in app.revanced.android.gms:layout/settings_root_activity: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.IllegalArgumentException: Cursor for query content://app.revanced.android.gms.microg.settings/exposureNotification [exposure_scanner_enabled] was null
	at org.microg.gms.settings.SettingsContract$getSettings$1.invoke(SettingsContract.kt:210)
	at org.microg.gms.settings.SettingsContract.withoutCallingIdentity(SettingsContract.kt:200)
	at org.microg.gms.settings.SettingsContract.getSettings(SettingsContract.kt:207)
	at org.microg.gms.nearby.exposurenotification.ExposurePreferences.getEnabled(ExposurePreferences.kt:19)
	at org.microg.gms.nearby.exposurenotification.ui.ExposureNotificationsSettingsProvider.getEntriesStatic(ExposureNotificationsSettingsProvider.kt:27)
	at org.microg.gms.ui.SettingsFragment.onCreatePreferences(SettingsFragment.kt:63)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1969)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:163)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:163)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:247)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:226)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:957)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:885)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1011)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1014)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at org.microg.gms.ui.MainSettingsActivity.onCreate(MainSettingsActivity.java:36)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8938)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1536)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4173)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by 813ethan** [comment]
it happens at evolution x latest build for poco f5/redmi note 12 turbo, never happened before though

**Comment by 813ethan** [comment]
when opening microg settings the app would be immediately crashed with this log

**Comment by 813ethan** [comment]
erased all data in microg and the crash still happens

**Comment by 813ethan** [comment]
https://github.com/user-attachments/assets/4ac9e067-587f-46c3-9719-fa516b187694

**Comment by 813ethan** [comment]
same crash

**Comment by 813ethan** [comment]
cant install without root but ok

**Comment by trewer68** [comment]
same error
began to appear after updating to the last build of evolution
system: Evolution X 9.3 17/08 update
device: Google Pixel 7 pro

**Comment by oSumAtrIX** [comment]
Quite sure issue is upstream. Once they fix it we can pull here

**Comment by joeyhuab** [comment]
This has been resolved in our source. Kindly close the issue.
