### ISSUE TITLE
bug: App crashes when trying to add a account.

### ISSUE THREAD

**Issue by starterbeeee** [ReVanced/GmsCore#87]
My device is a Samsung Galaxy S7 Edge (Exynos)
Model: G935FD 
Region: XSG
Android: 7.0
Going into the MicroG settings, then into Google Account and trying to log in crashes MicroG.
Same goes if you try to log in from any other app (i.e: Youtube, Youtube Music).
[logcat.txt](https://github.com/user-attachments/files/15526545/logcat.txt)

**Comment by oSumAtrIX** [comment]
The attached logs don't contain any crash logs.

**Comment by starterbeeee** [comment]
Apologies, it's my first time using adb's logcat, perhaps these do?
[logcat.txt](https://github.com/user-attachments/files/15526579/logcat.txt)
Here's a screenshot of what happened after i clicked log in:
![Screenshot_20240602-151856](https://github.com/ReVanced/GmsCore/assets/83183177/fd1b91a4-61fe-44ed-84c2-e90666c6d411)

**Comment by oSumAtrIX** [comment]
The issue is not caused by ReVanced or even upstream. I think this is an issue with your device/Chrome installation. 

```
06-02 15:18:17.077 13603 13603 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException                                                 06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)                                    06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)                              06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)                           06-02 15:18:17.077 13603 13603 E AndroidRuntime:        ... 26 more         06-02 15:18:17.077 13603 13603 E AndroidRuntime: Caused by: org.chromium.base.library_loader.ProcessInitException: errorCode=2                          06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at org.chromium.base.library_loader.b.i(chromium-Monochrome.aab-stable-604519420:172)           06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at org.chromium.base.library_loader.b.j(chromium-Monochrome.aab-stable-604519420:28)            06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at org.chromium.android_webview.AwBrowserProcess.i(chromium-Monochrome.aab-stable-604519420:34) 06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-Monochrome.aab-stable-604519420:451)                                                         06-02 15:18:17.077 13603 13603 E AndroidRuntime:        ... 29 more         06-02 15:18:17.077 13603 13603 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.chrome-1/lib/arm/libmonochrome.so" is 32-bit instead of 64-bit                                    06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:977)                                             06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1567)                                               06-02 15:18:17.077 13603 13603 E AndroidRuntime:        at org.chromium.base.library_loader.b.i(chromium-Monochrome.aab-stable-604519420:52)            06-02 15:18:17.077 13603 13603 E AndroidRuntime:        ... 32 more
```
